# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 99) do

  create_table "policies", :force => true do |t|
    t.column "type",              :string
    t.column "name",              :string
    t.column "zone",              :integer
    t.column "zonetype",          :string
    t.column "domain",            :integer
    t.column "domaintype",        :string
    t.column "resource",          :integer
    t.column "resourcetype",      :string
    t.column "resource_list",     :string
    t.column "replica_method_id", :integer
  end

  create_table "r_domains", :force => true do |t|
    t.column "name",       :string
    t.column "zone_id",    :integer
    t.column "created_at", :datetime, :default => '2007-08-23 13:53:10'
  end

  create_table "r_files", :force => true do |t|
    t.column "path",       :text
    t.column "name",       :string
    t.column "user_id",    :integer
    t.column "policy_id",  :integer
    t.column "created_at", :datetime, :default => '2007-08-23 13:53:10'
  end

  create_table "r_locations", :force => true do |t|
    t.column "name",       :string
    t.column "host",       :string
    t.column "port",       :integer
    t.column "domain_id",  :integer
    t.column "created_at", :datetime, :default => '2007-08-16 14:44:05'
  end

  create_table "r_resources", :force => true do |t|
    t.column "name",       :string
    t.column "address",    :string
    t.column "downtime",   :integer,  :default => 0
    t.column "domain_id",  :integer
    t.column "online",     :boolean
    t.column "created_at", :datetime, :default => '2007-08-23 13:53:10'
    t.column "updated_at", :datetime
  end

  create_table "r_users", :force => true do |t|
    t.column "userset_id", :integer
    t.column "username",   :string
    t.column "password",   :string
    t.column "domain_id",  :integer
    t.column "created_at", :datetime, :default => '2007-08-23 13:53:10'
  end

  create_table "r_zones", :force => true do |t|
    t.column "name",       :string
    t.column "host",       :string
    t.column "port",       :integer
    t.column "created_at", :datetime, :default => '2007-08-23 13:53:10'
  end

  create_table "replica_logs", :force => true do |t|
    t.column "file_id",        :integer
    t.column "action",         :string
    t.column "replica_number", :integer
    t.column "resource",       :string
    t.column "success",        :boolean
    t.column "created_at",     :datetime, :default => '2007-08-23 13:53:10'
  end

  create_table "replica_methods", :force => true do |t|
    t.column "type", :string
  end

end
